# Generated by Django 5.0.3 on 2024-05-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_variations'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
